# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: async_messaging/publisher_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'async_messaging/publisher_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'async_messaging/publisher_service.proto\x12 accelbyte.extend.async_messaging\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/descriptor.proto\"\xbe\x01\n\x15PublishMessageRequest\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12W\n\x08metadata\x18\x03 \x03(\x0b\x32\x45.accelbyte.extend.async_messaging.PublishMessageRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x85\x01\n\x1e\x41syncMessagingPublisherService\x12\x63\n\x0ePublishMessage\x12\x37.accelbyte.extend.async_messaging.PublishMessageRequest\x1a\x16.google.protobuf.Empty\"\x00\x42n\n#net.accelbyte.extend.asyncMessagingP\x01Z#accelbyte.net/extend/asyncMessaging\xaa\x02\x1f\x41\x63\x63\x65lByte.Extend.AsyncMessagingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_messaging.publisher_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#net.accelbyte.extend.asyncMessagingP\001Z#accelbyte.net/extend/asyncMessaging\252\002\037AccelByte.Extend.AsyncMessaging'
  _globals['_PUBLISHMESSAGEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PUBLISHMESSAGEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_start=198
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_end=388
  _globals['_PUBLISHMESSAGEREQUEST_METADATAENTRY']._serialized_start=341
  _globals['_PUBLISHMESSAGEREQUEST_METADATAENTRY']._serialized_end=388
  _globals['_ASYNCMESSAGINGPUBLISHERSERVICE']._serialized_start=391
  _globals['_ASYNCMESSAGINGPUBLISHERSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
